// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	LCU "Coattails/core/internal/handler/LCU"
	"Coattails/core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/from/:name",
					Handler: LCU.CoattailsHandler(serverCtx),
				},
			}...,
		),
	)
}
